### ISSUE TITLE
Publish in the Snap Store

### ISSUE THREAD

**Issue by felicianotech** [LanceGundersen/navfit2020#70]
Hey, as I mentioned in the FB group I see that you're producing a snap package but I didn't find this project in the Snap Store. While there is some work to do, publishing in the Snap Store doesn't cost money as it would in Google Play or the App Store. I have several personal snaps in the store and I maintain the CircleCI snap as well. If there's interest here, I can help with the continuous deployment process for getting a snap published via CircleCI automatically.

Here's one of my projects where I do this now: https://github.com/felicianotech/sonar/blob/master/.circleci/config.yml#L122

This example is likely a bit more complicated than you would need though as it doesn multiple architectures and edge releases. One for NavFit2020 could be simpler.

**Comment by LanceGundersen** [comment]
@felicianotech good call. I have it up and linked with the new snapcraft build service so was pretty straightforward after I debugged the yaml file. Check it out https://snapcraft.io/navfit

If you get a chance can you pull it and see if it runs fine?

**Comment by FelicianoTech** [comment]
Apologies for the delay. I did get around to installing and attempting to run it. There's issues.

![Screenshot from 2020-12-12 23-17-08](https://user-images.githubusercontent.com/6017470/102003081-d2a7ab80-3cd0-11eb-8c14-f231bab099d8.png)

1.There two blockers that prevent people from easily installing it.
  a. The snap it published only to the `edge` channel. I completely get why you did this however I don't recommend it for a new application. This is because when installing, people will get the warning/error that I did and have to reconfigure the command to get it to install. Additionally, this prevents your app from appearing in the Snap Store search, the Ubuntu Software search, at all for the time being. Someone would have to magically know it's available in order to install it. My recommendation is to only use the `edge` channel when there's already a stable release and you want to provide two different channels for users to install the snap.
  b. In the same vein, the snap was marked as not a stable release in `snapcraft.yaml` which gives me an additional warning/error when installing. This leads to yet another flag I now need to use in order to install the name. My recommendation for this is to build snaps with a grade of "devel" only when they're distributed outside of the Snap Store. I don't see a reason to do otherwise. Again, this is a personal opinion based on my experience building and publishing snaps.
2. It doesn't work. Once I finally got the snap installed, I couldn't find the application in my launcher. Taking a look at the `snapcraft.yml` file I see this is because the file is not creating a command within the snap. It's missing a major piece.

**Comment by LanceGundersen** [comment]
@felicianotech good catch on 2, that is definitely missing. Regarding the edge channel, I wanted to ensure the bugs/tweaks were flushed out like in your findings on 2. Once confirmed working I can push it to a stable branch. I will ping you again when I have it to where I think it's working.

**Comment by LanceGundersen** [comment]
sd

**Comment by FelicianoTech** [comment]
Sure. I'm happy to tackle this one if you want to delegate. Just let me know. I'll keep an eye on new issues as well.

**Comment by LanceGundersen** [comment]
@felicianotech can you see if it is working for you now?

**Comment by FelicianoTech** [comment]
Yup. It loads up just fine now. The icon shows in the launcher correctly as well. When I click the hamburger menu at the top left, a panel slides out like 5 pixels and that's it. 
![Screenshot from 2020-12-18 14-35-56](https://user-images.githubusercontent.com/6017470/102655147-ccd22000-413f-11eb-8b80-ce6bb836f4b9.png)

If that's not a snap related issue, then I'd say this issue can be closed.

**Comment by LanceGundersen** [comment]
Thanks for reviewing @felicianotech. Yeah the menu only populates when you have sailors in the database. A button to add a sailor on an empty array will be added in the future there.
